spring:
  application:
    name: auth-service
  main:
    banner-mode: off
  datasource:
    url: postgresql://localhost:5432/auth_user_db
    username: postgres
    password: Jagadish@99
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
        format_sql: true